steps:
  # Build frontend
  - name: 'node:18'
    id: 'Build-Frontend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd frontend
        npm ci
        npm run build
    env:
      - 'NODE_ENV=production'
      - 'REACT_APP_API_URL=https://ragscholarai-432924679896.europe-west2.run.app/api/v1'

  # Deploy frontend to Firebase (using service account)
  - name: 'node:18'
    id: 'Deploy-Frontend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd frontend
        npm install -g firebase-tools
        echo "$$FIREBASE_SERVICE_ACCOUNT" > /tmp/service-account.json
        export GOOGLE_APPLICATION_CREDENTIALS=/tmp/service-account.json
        firebase deploy --only hosting --project ${_FIREBASE_PROJECT_ID}
    secretEnv: ['FIREBASE_SERVICE_ACCOUNT']
    waitFor: ['Build-Frontend']

# Options for optimization
options:
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: ALLOW_LOOSE
  # Enable faster builds
  machineType: E2_HIGHCPU_8
  diskSizeGb: 100

# Environment substitutions
substitutions:
  _FIREBASE_PROJECT_ID: ragscholarai

# Available secrets (Firebase service account from Secret Manager)
availableSecrets:
  secretManager:
    - versionName: projects/tough-canto-471207-p6/secrets/firebase-service-account/versions/latest
      env: 'FIREBASE_SERVICE_ACCOUNT'

tags:
    - frontend-only
    - ragscholarai-frontend
