services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - PYTHONPATH=/app/src
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
    env_file:
      - .env
      - .env.local
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ~/.config/gcloud/application_default_credentials.json:/app/credentials.json
    command: ["python", "-m", "uvicorn", "rag_scholar.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api/v1
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    command: ["npm", "start"]
    depends_on:
      - backend

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: