services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - PYTHONPATH=/app/src
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
      - GOOGLE_CLOUD_PROJECT=ragscholarai
      # Doppler configuration for secure secret management
      - DOPPLER_PROJECT=rag-scholar
      - DOPPLER_CONFIG=dev
    # Environment variables provided by Doppler
    volumes:
      - ./src:/app/src
      - ~/.config/gcloud/application_default_credentials.json:/app/credentials.json
    # Use Doppler for secure secret injection in development
    command: ["python", "-m", "uvicorn", "rag_scholar.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api/v1
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    command: ["npm", "start"]
    depends_on:
      - backend

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"